name: CI/CD Pipeline

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm i

      - name: Run Tests
        run: npm run test

  deploy:
    needs: test
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sync Files to Production
        run: rsync -av --delete ./ /home/ubuntu/github-action-ci-cd/

      - name: Install Production Dependencies
        run: |
          cd /home/ubuntu/github-action-ci-cd
          npm i --production

      - name: Restart App
        run: pm2 restart backend-prod