name: CI/CD Pipeline

on:
  push:
    branches: [master]

jobs:
  ci:
    runs-on: self-hosted

    steps:
      # 1. Download your fresh code into the safe runner playground folder
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      # 2. Copy the fresh files over to your active app folder
      - name: Sync Code to App Directory
        run: |
          cp -R ./* /home/ubuntu/github-action-ci-cd/

      # 3. Go to your app folder and install dependencies
      - name: Install Dependencies
        run: |
          cd /home/ubuntu/github-action-ci-cd
          npm i

      # 4. Run tests
      - name: Run Test
        run: |
          cd /home/ubuntu/github-action-ci-cd
          npm run test

  cd:
    needs: ci
    runs-on: self-hosted

    steps:
      - name: Restart App
        run: |
          pm2 reload backend
